name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-android:
    runs-on: ubuntu-latest
    name: Android E2E Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Create Android Virtual Device
      run: |
        echo "Creating Android Virtual Device..."
        echo "no" | avdmanager create avd \
          -n "Pixel_5_API_30" \
          -k "system-images;android-30;google_apis;x86_64" \
          -d "pixel_5" \
          -f

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Pixel_5
        avd-name: Pixel_5_API_30
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none -memory 2048 -cores 2
        script: |
          cd mobile
          npm install
          npm run e2e:build
          npm run e2e:test

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: android-e2e-artifacts
        path: |
          mobile/android/app/build/outputs/apk/debug/
          mobile/e2e/artifacts/

  e2e-ios:
    runs-on: macos-latest
    name: iOS E2E Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install iOS dependencies
      run: |
        cd mobile
        npm install
        cd ios
        pod install

    - name: Build iOS app
      run: |
        cd mobile
        npm run e2e:build:ios

    - name: Run iOS E2E tests
      run: |
        cd mobile
        npm run e2e:test:ios

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ios-e2e-artifacts
        path: |
          mobile/ios/build/Build/Products/Debug-iphonesimulator/
          mobile/e2e/artifacts/

  test-report:
    runs-on: ubuntu-latest
    needs: [e2e-android, e2e-ios]
    if: always()
    name: Generate Test Report
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Android artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-e2e-artifacts
        path: android-artifacts

    - name: Download iOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: ios-e2e-artifacts
        path: ios-artifacts

    - name: Generate test summary
      run: |
        echo "## E2E Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ needs.e2e-android.result }}" == "success" ]; then
          echo "✅ **Android E2E Tests**: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Android E2E Tests**: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.e2e-ios.result }}" == "success" ]; then
          echo "✅ **iOS E2E Tests**: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **iOS E2E Tests**: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Coverage" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Main Screen Navigation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Note Creation & Validation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Note Editing & Deletion" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ API Integration" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Error Handling" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Settings & Language" >> $GITHUB_STEP_SUMMARY
